In [74]:
from os import getcwd
import pandas as pd
import numpy as np
import scipy.stats as stats
import re
from functools import reduce
from itertools import combinations

In [2]:
MLB = getcwd() + "\\resources\\mlb.csv"
NBA = getcwd() + "\\resources\\nba.csv"
NFL = getcwd() + "\\resources\\nfl.csv"
NHL = getcwd() + "\\resources\\nhl.csv"
Wikipedia = getcwd() + "\\resources\\wikipedia_data.html"

In [3]:
MLBdata = pd.read_csv(MLB)
NBAdata = pd.read_csv(NBA)
NFLdata = pd.read_csv(NFL)
NHLdata = pd.read_csv(NHL)
Wikidata = pd.read_html(Wikipedia)

In [4]:
WikiData = Wikidata[1]

In [5]:
WikiData.replace(r'\[note \d*\]','',regex=True,inplace=True)

In [170]:
cities = WikiData.iloc[:-1,[0,3,5,6,7,8]]
cities.replace("",np.nan,inplace=True)
cities.replace("—",np.nan,inplace=True)
cities.replace("— ",np.nan,inplace=True)
cities.rename(columns = {'Population (2016 est.)[8]':'Population'},inplace=True)
cities

,Metropolitan area,Population,NFL,MLB,NBA,NHL
0,New York City,20153634,GiantsJets,YankeesMets,KnicksNets,RangersIslandersDevils
1,Los Angeles,13310447,RamsChargers,DodgersAngels,LakersClippers,KingsDucks
2,San Francisco Bay Area,6657982,49ersRaiders,GiantsAthletics,Warriors,Sharks
3,Chicago,9512999,Bears,CubsWhite Sox,Bulls,Blackhawks
4,Dallas–Fort Worth,7233323,Cowboys,Rangers,Mavericks,Stars
5,"Washington, D.C.",6131977,Redskins,Nationals,Wizards,Capitals
6,Philadelphia,6070500,Eagles,Phillies,76ers,Flyers
7,Boston,4794447,Patriots,Red Sox,Celtics,Bruins
8,Minneapolis–Saint Paul,3551036,Vikings,Twins,Timberwolves,Wild
9,Denver,2853077,Broncos,Rockies,Nuggets,Avalanche
10,Miami–Fort Lauderdale,6066387,Dolphins,Marlins,Heat,Panthers
11,Phoenix,4661537,Cardinals,Diamondbacks,Suns,Coyotes
12,Detroit,4297617,Lions,Tigers,Pistons,Red Wings
13,Toronto,5928040,NaN,Blue Jays,Raptors,Maple Leafs
14,Houston,6772470,Texans,Astros,Rockets,NaN
15,Atlanta,5789700,Falcons,Braves,Hawks,NaN
16,Tampa Bay Area,3032171,Buccaneers,Rays,NaN,Lightning
17,Pittsburgh,2342299,Steelers,Pirates,NaN,Penguins
18,Cleveland,2055612,Browns,Indians,Cavaliers,NaN
19,Seattle,3798902,Seahawks,Mariners,NaN,NaN
20,Cincinnati,2165139,Bengals,Reds,NaN,NaN
21,Kansas City,2104509,Chiefs,Royals,NaN,NaN
22,St. Louis,2807002,NaN,Cardinals,NaN,Blues
23,Baltimore,2798886,Ravens,Orioles,NaN,NaN
24,Charlotte,2474314,Panthers,NaN,Hornets,NaN
25,Indianapolis,2004230,Colts,NaN,Pacers,NaN
26,Nashville,1865298,Titans,NaN,NaN,Predators
27,Milwaukee,1572482,NaN,Brewers,Bucks,NaN
28,New Orleans,1268883,Saints,NaN,Pelicans,NaN
29,Buffalo,1132804,Bills,NaN,NaN,Sabres
30,Montreal,4098927,NaN,NaN,NaN,Canadiens
31,Vancouver,2463431,NaN,NaN,NaN,Canucks
32,Orlando,2441257,NaN,NaN,Magic,NaN
33,Portland,2424955,NaN,NaN,Trail Blazers,NaN
34,Columbus,2041520,NaN,NaN,NaN,Blue Jackets
35,Calgary,1392609,NaN,NaN,NaN,Flames
36,Ottawa,1323783,NaN,NaN,NaN,Senators
37,Edmonton,1321426,NaN,NaN,NaN,Oilers
38,Salt Lake City,1186187,NaN,NaN,Jazz,NaN
39,Winnipeg,778489,NaN,NaN,NaN,Jets
40,San Diego,3317749,NaN,Padres,NaN,NaN
41,San Antonio,2429609,NaN,NaN,Spurs,NaN
42,Sacramento,2296418,NaN,NaN,Kings,NaN
43,Las Vegas,2155664,NaN,NaN,NaN,Golden Knights
44,Jacksonville,1478212,Jaguars,NaN,NaN,NaN
45,Oklahoma City,1373211,NaN,NaN,Thunder,NaN
46,Memphis,1342842,NaN,NaN,Grizzlies,NaN
47,Raleigh,1302946,NaN,NaN,NaN,Hurricanes
48,Green Bay,318236,Packers,NaN,NaN,NaN
49,Hamilton,747545,NaN,NaN,NaN,NaN
50,Regina,236481,NaN,NaN,NaN,NaN

# NHL

In [199]:
NHLdata["year"].unique()

array([2018, 2017, 2015, 2014], dtype=int64)

In [200]:
NHLdata2018 = NHLdata[NHLdata["year"] == 2018]

In [201]:
dictionary = {
            "Atlantic Division" : NHLdata2018[1:9],
            "Metropolitan Division" : NHLdata2018[10:18],
            "Central Division" : NHLdata2018[19:26],
            "Pacific Division" : NHLdata2018[27:35]
}

In [202]:
dfDivs = [v.set_index(pd.MultiIndex.from_arrays([[k]*len(v),list(range(0,len(v)))])) for k,v in dictionary.items()]

In [203]:
NHLdata2018 = reduce(lambda x,y : x.append(y),dfDivs)
NHLdata2018

                                           team  GP   W   L  OL  PTS  PTS%  \
Atlantic Division     0    Tampa Bay Lightning*  82  54  23   5  113  .689
                      1          Boston Bruins*  82  50  20  12  112  .683
                      2    Toronto Maple Leafs*  82  49  26   7  105  .640
                      3        Florida Panthers  82  44  30   8   96  .585
                      4       Detroit Red Wings  82  30  39  13   73  .445
                      5      Montreal Canadiens  82  29  40  13   71  .433
                      6         Ottawa Senators  82  28  43  11   67  .409
                      7          Buffalo Sabres  82  25  45  12   62  .378
Metropolitan Division 0    Washington Capitals*  82  49  26   7  105  .640
                      1    Pittsburgh Penguins*  82  47  29   6  100  .610
                      2    Philadelphia Flyers*  82  42  26  14   98  .598
                      3  Columbus Blue Jackets*  82  45  30   7   97  .591
                      4      New Jersey Devils*  82  44  29   9   97  .591
                      5     Carolina Hurricanes  82  36  35  11   83  .506
                      6      New York Islanders  82  35  37  10   80  .488
                      7        New York Rangers  82  34  39   9   77  .470
Central Division      0    Nashville Predators*  82  53  18  11  117  .713
                      1          Winnipeg Jets*  82  52  20  10  114  .695
                      2         Minnesota Wild*  82  45  26  11  101  .616
                      3     Colorado Avalanche*  82  43  30   9   95  .579
                      4         St. Louis Blues  82  44  32   6   94  .573
                      5            Dallas Stars  82  42  32   8   92  .561
                      6      Chicago Blackhawks  82  33  39  10   76  .463
Pacific Division      0   Vegas Golden Knights*  82  51  24   7  109  .665
                      1          Anaheim Ducks*  82  44  25  13  101  .616
                      2        San Jose Sharks*  82  45  27  10  100  .610
                      3      Los Angeles Kings*  82  45  29   8   98  .598
                      4          Calgary Flames  82  37  35  10   84  .512
                      5         Edmonton Oilers  82  36  40   6   78  .476
                      6       Vancouver Canucks  82  31  40  11   73  .445
                      7         Arizona Coyotes  82  29  41  12   70  .427

                          GF   GA    SRS    SOS  RPt% ROW  year League
Atlantic Division     0  296  236   0.66  -0.07  .634  48  2018    NHL
                      1  270  214   0.62  -0.07  .610  47  2018    NHL
                      2  277  232   0.49  -0.06  .567  42  2018    NHL
                      3  248  246  -0.01  -0.04  .537  41  2018    NHL
                      4  217  255  -0.48  -0.01  .341  25  2018    NHL
                      5  209  264  -0.68   0.00  .378  27  2018    NHL
                      6  221  291  -0.85   0.00  .372  26  2018    NHL
                      7  199  280  -0.98   0.01  .311  24  2018    NHL
Metropolitan Division 0  259  239   0.21  -0.04  .585  46  2018    NHL
                      1  272  250   0.23  -0.04  .573  45  2018    NHL
                      2  251  243   0.07  -0.03  .543  40  2018    NHL
                      3  242  230   0.11  -0.04  .537  39  2018    NHL
                      4  248  244   0.02  -0.03  .530  39  2018    NHL
                      5  228  256  -0.35  -0.01  .439  33  2018    NHL
                      6  264  296  -0.40  -0.01  .427  32  2018    NHL
                      7  231  268  -0.46  -0.01  .427  31  2018    NHL
Central Division      0  267  211   0.71   0.03  .652  47  2018    NHL
                      1  277  218   0.74   0.02  .622  48  2018    NHL
                      2  253  232   0.29   0.04  .549  42  2018    NHL
                      3  257  237   0.28   0.04  .518  41  2018    NHL
                      4  226  222   0.10   0.05  .518  41  2018    NHL
                      5  235  225   0.17   0.04  .506  38  2018    NHL
                      6  229  256  -0.26   0.07  .409  32  2018    NHL
Pacific Division      0  272  228   0.52  -0.01  .616  47  2018    NHL
                      1  235  216   0.24   0.01  .555  40  2018    NHL
                      2  252  229   0.28   0.00  .537  40  2018    NHL
                      3  239  203   0.44   0.00  .543  43  2018    NHL
                      4  218  248  -0.33   0.03  .470  35  2018    NHL
                      5  234  263  -0.32   0.03  .415  31  2018    NHL
                      6  218  264  -0.51   0.05  .409  31  2018    NHL
                      7  208  256  -0.53   0.05  .372  27  2018    NHL

In [205]:
#NHLdata2018["team"].replace(to_replace=r'([^\*]*)(\*)',value=r'\1',regex=True,inplace=True)
NHLdata2018["team"].replace(to_replace=r'\*$',value=r'',regex=True,inplace=True)

In [206]:
NHLdata2018WR = NHLdata2018[["team","W","L"]].copy()
df_wr = NHLdata2018WR["W"].astype(int).divide(NHLdata2018WR["W"].astype(int) + NHLdata2018WR["L"].astype(int))
df_wr.name = "WR"
NHLdata2018WR = NHLdata2018WR.merge(df_wr,right_index=True,left_index=True)
del NHLdata2018WR["L"]
del NHLdata2018WR["W"]
NHLdata2018WR

                                          team        WR
Atlantic Division     0    Tampa Bay Lightning  0.701299
                      1          Boston Bruins  0.714286
                      2    Toronto Maple Leafs  0.653333
                      3       Florida Panthers  0.594595
                      4      Detroit Red Wings  0.434783
                      5     Montreal Canadiens  0.420290
                      6        Ottawa Senators  0.394366
                      7         Buffalo Sabres  0.357143
Metropolitan Division 0    Washington Capitals  0.653333
                      1    Pittsburgh Penguins  0.618421
                      2    Philadelphia Flyers  0.617647
                      3  Columbus Blue Jackets  0.600000
                      4      New Jersey Devils  0.602740
                      5    Carolina Hurricanes  0.507042
                      6     New York Islanders  0.486111
                      7       New York Rangers  0.465753
Central Division      0    Nashville Predators  0.746479
                      1          Winnipeg Jets  0.722222
                      2         Minnesota Wild  0.633803
                      3     Colorado Avalanche  0.589041
                      4        St. Louis Blues  0.578947
                      5           Dallas Stars  0.567568
                      6     Chicago Blackhawks  0.458333
Pacific Division      0   Vegas Golden Knights  0.680000
                      1          Anaheim Ducks  0.637681
                      2        San Jose Sharks  0.625000
                      3      Los Angeles Kings  0.608108
                      4         Calgary Flames  0.513889
                      5        Edmonton Oilers  0.473684
                      6      Vancouver Canucks  0.436620
                      7        Arizona Coyotes  0.414286

In [208]:
citiesNHL = cities[["Metropolitan area","Population","NHL"]].dropna()

In [209]:
dictNHL = [
    {"Metropolitan area":"New York City","Population":20153634,"NHL":"Rangers"},
    {"Metropolitan area":"New York City","Population":20153634,"NHL":"Islanders"},
    {"Metropolitan area":"New York City","Population":20153634,"NHL":"Devils"},
    {"Metropolitan area":"Los Angeles","Population":13310447,"NHL":"Kings"},
    {"Metropolitan area":"Los Angeles","Population":13310447,"NHL":"Ducks"}
]

citiesNHL = citiesNHL.append(dictNHL,ignore_index=True)
citiesNHL.drop([0,1],inplace=True)
citiesNHL

         Metropolitan area Population             NHL
2   San Francisco Bay Area    6657982          Sharks
3                  Chicago    9512999      Blackhawks
4        Dallas–Fort Worth    7233323           Stars
5         Washington, D.C.    6131977        Capitals
6             Philadelphia    6070500          Flyers
7                   Boston    4794447          Bruins
8   Minneapolis–Saint Paul    3551036            Wild
9                   Denver    2853077       Avalanche
10   Miami–Fort Lauderdale    6066387        Panthers
11                 Phoenix    4661537         Coyotes
12                 Detroit    4297617       Red Wings
13                 Toronto    5928040     Maple Leafs
14          Tampa Bay Area    3032171       Lightning
15              Pittsburgh    2342299        Penguins
16               St. Louis    2807002           Blues
17               Nashville    1865298       Predators
18                 Buffalo    1132804          Sabres
19                Montreal    4098927       Canadiens
20               Vancouver    2463431         Canucks
21                Columbus    2041520    Blue Jackets
22                 Calgary    1392609          Flames
23                  Ottawa    1323783        Senators
24                Edmonton    1321426          Oilers
25                Winnipeg     778489            Jets
26               Las Vegas    2155664  Golden Knights
27                 Raleigh    1302946      Hurricanes
28           New York City   20153634         Rangers
29           New York City   20153634       Islanders
30           New York City   20153634          Devils
31             Los Angeles   13310447           Kings
32             Los Angeles   13310447           Ducks

In [210]:
NHLdata2018WR["team"].replace(r'(.*)( )(\w*)$',r'\3',regex=True,inplace=True)
fixNames = {
    "Jackets" : "Blue Jackets",
    "Wings" : "Red Wings",
    "Leafs" : "Maple Leafs",
    "Knights" : "Golden Knights"
}
NHLdata2018WR["team"].replace(fixNames,inplace=True)
NHLdata2018WR

                                   team        WR
Atlantic Division     0       Lightning  0.701299
                      1          Bruins  0.714286
                      2     Maple Leafs  0.653333
                      3        Panthers  0.594595
                      4       Red Wings  0.434783
                      5       Canadiens  0.420290
                      6        Senators  0.394366
                      7          Sabres  0.357143
Metropolitan Division 0        Capitals  0.653333
                      1        Penguins  0.618421
                      2          Flyers  0.617647
                      3    Blue Jackets  0.600000
                      4          Devils  0.602740
                      5      Hurricanes  0.507042
                      6       Islanders  0.486111
                      7         Rangers  0.465753
Central Division      0       Predators  0.746479
                      1            Jets  0.722222
                      2            Wild  0.633803
                      3       Avalanche  0.589041
                      4           Blues  0.578947
                      5           Stars  0.567568
                      6      Blackhawks  0.458333
Pacific Division      0  Golden Knights  0.680000
                      1           Ducks  0.637681
                      2          Sharks  0.625000
                      3           Kings  0.608108
                      4          Flames  0.513889
                      5          Oilers  0.473684
                      6         Canucks  0.436620
                      7         Coyotes  0.414286

In [230]:
mergedNHL = NHLdata2018WR.merge(citiesNHL,left_on="team",right_on="NHL")
mergedNHL.drop("NHL",axis=1,inplace=True)
mergedNHL.set_index("Metropolitan area",inplace=True)
mergedNHL = mergedNHL.sort_index()

In [234]:
wr_region = mergedNHL.groupby(by="Metropolitan area").mean().copy()
wr_region

                              WR
Metropolitan area
Boston                  0.714286
Buffalo                 0.357143
Calgary                 0.513889
Chicago                 0.458333
Columbus                0.600000
Dallas–Fort Worth       0.567568
Denver                  0.589041
Detroit                 0.434783
Edmonton                0.473684
Las Vegas               0.680000
Los Angeles             0.622895
Miami–Fort Lauderdale   0.594595
Minneapolis–Saint Paul  0.633803
Montreal                0.420290
Nashville               0.746479
New York City           0.518201
Ottawa                  0.394366
Philadelphia            0.617647
Phoenix                 0.414286
Pittsburgh              0.618421
Raleigh                 0.507042
San Francisco Bay Area  0.625000
St. Louis               0.578947
Tampa Bay Area          0.701299
Toronto                 0.653333
Vancouver               0.436620
Washington, D.C.        0.653333
Winnipeg                0.722222

In [232]:
population_region = mergedNHL["Population"].drop_duplicates().astype(float).to_frame().copy()
population_region

                        Population
Metropolitan area
Boston                   4794447.0
Buffalo                  1132804.0
Calgary                  1392609.0
Chicago                  9512999.0
Columbus                 2041520.0
Dallas–Fort Worth        7233323.0
Denver                   2853077.0
Detroit                  4297617.0
Edmonton                 1321426.0
Las Vegas                2155664.0
Los Angeles             13310447.0
Miami–Fort Lauderdale    6066387.0
Minneapolis–Saint Paul   3551036.0
Montreal                 4098927.0
Nashville                1865298.0
New York City           20153634.0
Ottawa                   1323783.0
Philadelphia             6070500.0
Phoenix                  4661537.0
Pittsburgh               2342299.0
Raleigh                  1302946.0
San Francisco Bay Area   6657982.0
St. Louis                2807002.0
Tampa Bay Area           3032171.0
Toronto                  5928040.0
Vancouver                2463431.0
Washington, D.C.         6131977.0
Winnipeg                  778489.0

In [233]:
stats.pearsonr(population_region["Population"], wr_region["WR"])

(0.012486162921209923, 0.9497182859911781)

# NBA

In [21]:
citiesNBA = cities[["Metropolitan area","Population","NBA"]].dropna()

In [22]:
dictNBA = [
    {"Metropolitan area":"New York City","Population":20153634,"NBA":"Knicks"},
    {"Metropolitan area":"New York City","Population":20153634,"NBA":"Nets"},
    {"Metropolitan area":"Los Angeles","Population":13310447,"NBA":"Lakers"},
    {"Metropolitan area":"Los Angeles","Population":13310447,"NBA":"Clippers"}
]

citiesNBA = citiesNBA.append(dictNBA,ignore_index=True)
citiesNBA.drop([0,1],inplace=True)

In [23]:
NBAdata2018 = NBAdata[NBAdata["year"] == 2018].copy()

In [24]:
NBAdata2018["team"].replace(r"\*\s\(\d*\)$|\s\(\d*\)$","",regex=True,inplace=True)

In [25]:
NBAdata2018WR = NBAdata2018[["team","W","L"]].copy()

In [26]:
df_wr = NBAdata2018WR["W"].astype(int).divide(NBAdata2018WR["W"].astype(int) + NBAdata2018WR["L"].astype(int))
df_wr.name = "WR"
NBAdata2018WR = NBAdata2018WR.merge(df_wr,right_index=True,left_index=True)
del NBAdata2018WR["L"]
del NBAdata2018WR["W"]

In [27]:
NBAdata2018WR["team"].replace(r'(.*)( )(\w*)$',r'\3',regex=True,inplace=True)
fixNames = {"Blazers" : "Trail Blazers"}
NBAdata2018WR["team"].replace(fixNames,inplace=True)

In [28]:
mergedNBA = NBAdata2018WR.merge(citiesNBA,left_on="team",right_on="NBA")
mergedNBA.drop("NBA",axis=1,inplace=True)
mergedNBA.set_index("Metropolitan area",inplace=True)

In [29]:
wr_region = mergedNBA.groupby(by="Metropolitan area").mean().sort_values(by="Metropolitan area")

In [30]:
population_region = mergedNBA["Population"].drop_duplicates().astype(float).to_frame().sort_values(by="Metropolitan area")

In [31]:
stats.pearsonr(population_region["Population"], wr_region["WR"])

(-0.17657160252844623, 0.3687474160446294)

# MLB

In [32]:
citiesMLB = cities[["Metropolitan area","Population","MLB"]].dropna()

In [33]:
dictMLB = [
    {"Metropolitan area":"New York City","Population":20153634,"MLB":"Yankees"},
    {"Metropolitan area":"New York City","Population":20153634,"MLB":"Mets"},
    {"Metropolitan area":"Los Angeles","Population":13310447,"MLB":"Dodgers"},
    {"Metropolitan area":"Los Angeles","Population":13310447,"MLB":"Angels"},
    {"Metropolitan area":"Chicago","Population":9512999,"MLB":"Cubs"},
    {"Metropolitan area":"Chicago","Population":9512999,"MLB":"White Sox"},
    {"Metropolitan area":"San Francisco Bay Area","Population":6657982,"MLB":"Giants"},
    {"Metropolitan area":"San Francisco Bay Area","Population":6657982,"MLB":"Athletics"}
]

citiesMLB = citiesMLB.append(dictMLB,ignore_index=True)
citiesMLB.drop([0,1,2,3],inplace=True)

In [34]:
MLBdata2018 = MLBdata[MLBdata["year"] == 2018].copy()

In [35]:
MLBdata2018WR = MLBdata2018[["team","W","L"]].copy()

In [36]:
df_wr = MLBdata2018WR["W"].astype(int).divide(MLBdata2018WR["W"].astype(int) + MLBdata2018WR["L"].astype(int))
df_wr.name = "WR"
MLBdata2018WR = MLBdata2018WR.merge(df_wr,right_index=True,left_index=True)
del MLBdata2018WR["L"]
del MLBdata2018WR["W"]

In [37]:
MLBdata2018WR["team"].replace(r'(.*)( )(\w*)$',r'\3',regex=True,inplace=True)
fixNames = {"Jays" : "Blue Jays",}
MLBdata2018WR["team"].replace(fixNames,inplace=True)
MLBdata2018WR.at[0,"team"] = "Red Sox"
MLBdata2018WR.at[8,"team"] = "White Sox"

In [38]:
mergedMLB = MLBdata2018WR.merge(citiesMLB,left_on="team",right_on="MLB")
mergedMLB.drop("MLB",axis=1,inplace=True)
mergedMLB.set_index("Metropolitan area",inplace=True)

In [39]:
wr_region = mergedMLB.groupby(by="Metropolitan area").mean().sort_values(by="Metropolitan area")
population_region = mergedMLB["Population"].drop_duplicates().astype(float).to_frame().sort_values(by="Metropolitan area")

In [40]:
stats.pearsonr(population_region["Population"], wr_region["WR"])

(0.15027698302669307, 0.46370703378875583)

# NFL

In [41]:
citiesNFL = cities[["Metropolitan area","Population","NFL"]].dropna()

In [42]:
dictNFL = [
    {"Metropolitan area":"New York City","Population":20153634,"NFL":"Giants"},
    {"Metropolitan area":"New York City","Population":20153634,"NFL":"Jets"},
    {"Metropolitan area":"Los Angeles","Population":13310447,"NFL":"Rams"},
    {"Metropolitan area":"Los Angeles","Population":13310447,"NFL":"Chargers"},
    {"Metropolitan area":"San Francisco Bay Area","Population":6657982,"NFL":"49ers"}
]

citiesNFL = citiesNFL.append(dictNFL,ignore_index=True)
citiesNFL.drop([0,1,2],inplace=True)

In [62]:
NFLdata2018 = NFLdata[NFLdata["year"] == 2018].copy()

In [63]:
dictionary = {
            "AFC East" : NFLdata2018[1:5],
            "AFC North" : NFLdata2018[6:10],
            "AFC South" : NFLdata2018[11:15],
            "AFC West" : NFLdata2018[16:20],
            "NFC East" : NFLdata2018[21:25],
            "NFC North" : NFLdata2018[26:30],
            "NFC South" : NFLdata2018[31:35],
            "NFC West" : NFLdata2018[36:40]
}
dfDivs = [v.set_index(pd.MultiIndex.from_arrays([[k]*len(v),list(range(0,len(v)))])) for k,v in dictionary.items()]
NFLdata2018 = reduce(lambda x,y : x.append(y),dfDivs)

In [65]:
NFLdata2018["team"].replace(to_replace=r'[\*\+]',value=r'',regex=True,inplace=True)

In [46]:
NFLdata2018WR = NFLdata2018[["team","W","L"]].copy()
df_wr = NFLdata2018WR["W"].astype(int).divide(NFLdata2018WR["W"].astype(int) + NFLdata2018WR["L"].astype(int))
df_wr.name = "WR"
NFLdata2018WR = NFLdata2018WR.merge(df_wr,right_index=True,left_index=True)
del NFLdata2018WR["L"]
del NFLdata2018WR["W"]

In [47]:
NFLdata2018WR["team"].replace(r'(.*)( )(\w*)$',r'\3',regex=True,inplace=True)

In [48]:
mergedNFL = NFLdata2018WR.merge(citiesNFL,left_on="team",right_on="NFL")
mergedNFL.drop("NFL",axis=1,inplace=True)
mergedNFL.set_index("Metropolitan area",inplace=True)

In [49]:
wr_region = mergedNFL.groupby(by="Metropolitan area").mean().sort_values(by="Metropolitan area")
population_region = mergedNFL["Population"].drop_duplicates().astype(float).to_frame().sort_values(by="Metropolitan area")

In [168]:
stats.pearsonr(population_region["Population"], wr_region["WR"]).p-value

SyntaxError: unexpected character after line continuation character (<ipython-input-168-78aa94ca3253>, line 1)

In [51]:
def prepareData(file,divisions=False,divdict=None,regexClean=None,fixNames=None):
    data=pd.read_csv(file)
    data2018 = data[data["year"] == 2018]
    if divisions and divdict is not None:
        dfDivs = [v.set_index(pd.MultiIndex.from_arrays([[k]*len(v),list(range(0,len(v)))])) for k,v in divdict.items()]
        data2018 = reduce(lambda x,y : x.append(y),dfDivs)
    
    if regexClean is not None:
        data2018["team"].replace(to_replace=regexClean,value='',regex=True,inplace=True)

    data2018WR = data2018[["team","W","L"]].copy()
    df_wr = data2018WR["W"].astype(int).divide(data2018WR["W"].astype(int) + data2018WR["L"].astype(int))
    df_wr.name = "WR"
    data2018WR = data2018WR.merge(df_wr,right_index=True,left_index=True)
    del data2018WR["L"]
    del data2018WR["W"]
    
    data2018WR["team"].replace(r'(.*)(\s)(\w*)$',r'\3',regex=True,inplace=True)
    if fixNames is not None:
        data2018WR["team"].replace(fixNames,inplace=True)
    
    return data2018WR

In [66]:
def prepareCitiesLeagueData(leagueName,dictLeague,dropRows):
    cities = prepareCitiesData()
    citiesLeague = cities[["Metropolitan area","Population",leagueName]].dropna()

    citiesLeague = citiesLeague.append(dictLeague,ignore_index=True)
    citiesLeague.drop(dropRows,inplace=True)
    
    return citiesLeague

In [ ]:
def correlation(leagueName,dictLeague,dropRows,file,divisions=None,divdict=None,regexClean=None,fixNames=None): 
    
    cities = prepareCitiesLeagueData(leagueName,dictLeague,dropRows)
    data = prepareData(file,divisions,divdict,regexClean,fixNames)
    
    merged = data.merge(cities,left_on="team",right_on=leagueName)
    merged.drop(leagueName,axis=1,inplace=True)
    merged.set_index("Metropolitan area",inplace=True)
    
    wr_region = merged.groupby(by="Metropolitan area").mean().sort_values(by="Metropolitan area")
    population_region = merged["Population"].drop_duplicates().astype(float).to_frame().sort_values(by="Metropolitan area")

    population_by_region = population_region["Population"] # pass in metropolitan area population from cities
    win_loss_by_region = wr_region["WR"] # pass in win/loss ratio from nhl_df in the same order as cities["Metropolitan area"]

    assert len(population_by_region) == len(win_loss_by_region), "Q1: Your lists must be the same length"
    assert len(population_by_region) == 28, "Q1: There should be 28 teams being analysed for NHL"
    
    return stats.pearsonr(population_by_region, win_loss_by_region)

# Question 5

In [162]:
NHL_wr_region = mergedNHL.groupby(by="Metropolitan area").mean().sort_values(by="Metropolitan area")
NBA_wr_region = mergedNBA.groupby(by="Metropolitan area").mean().sort_values(by="Metropolitan area")
MLB_wr_region = mergedMLB.groupby(by="Metropolitan area").mean().sort_values(by="Metropolitan area")
NFL_wr_region = mergedNFL.groupby(by="Metropolitan area").mean().sort_values(by="Metropolitan area")

dictWRs = {
    "NHL" : NHL_wr_region,
    "NBA" : NBA_wr_region,
    "MLB" : MLB_wr_region,
    "NFL" : NFL_wr_region
}

In [163]:
sports = ['NFL', 'NBA', 'NHL', 'MLB']
p_values = pd.DataFrame({k:np.nan for k in sports}, index=sports)
c = combinations(sports,2)

In [164]:
for a,b in c:
    m = dictWRs[a].merge(dictWRs[b],left_index=True,right_index=True,suffixes=('_'+a,'_'+b))
    p = stats.ttest_rel(m["WR_"+a],m["WR_"+b]).pvalue
    p_values.loc[a,b] = p
    p_values.loc[b,a] = p

AttributeError: 'Series' object has no attribute 'merge'

In [161]:
p_values

          NFL       NBA       NHL       MLB
NFL       NaN  0.941792  0.030883  0.802069
NBA  0.941792       NaN  0.022297  0.950540
NHL  0.030883  0.022297       NaN  0.000708
MLB  0.802069  0.950540  0.000708       NaN